# Generated by Django 4.2 on 2026-03-03 00:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("EMPLOYEE", "Employee"), ("ADMIN", "Admin")],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="employee_code",
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
